//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTXMania2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DTXMania2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon DTXMania2 {
            get {
                object obj = ResourceManager.GetObject("DTXMania2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Failed to log on as AutoPlayer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_AutoPlayerでのログオンに失敗しました {
            get {
                return ResourceManager.GetString("TXT_AutoPlayerでのログオンに失敗しました", resourceCulture);
            }
        }
        
        /// <summary>
        ///   China position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_Chinaの表示位置 {
            get {
                return ResourceManager.GetString("TXT_Chinaの表示位置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now accepting inputs for the HID Keyboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_HIDKeyboardの受付を開始しました {
            get {
                return ResourceManager.GetString("TXT_HIDKeyboardの受付を開始しました", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDI IN [{0}] &apos;{1}&apos; started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_MidiInの受付を開始しました {
            get {
                return ResourceManager.GetString("TXT_MidiInの受付を開始しました", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_OFF {
            get {
                return ResourceManager.GetString("TXT_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_ON {
            get {
                return ResourceManager.GetString("TXT_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ride position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_Rideの表示位置 {
            get {
                return ResourceManager.GetString("TXT_Rideの表示位置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Splash position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_Splashの表示位置 {
            get {
                return ResourceManager.GetString("TXT_Splashの表示位置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_ウィンドウ {
            get {
                return ResourceManager.GetString("TXT_ウィンドウ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_オプション設定へ {
            get {
                return ResourceManager.GetString("TXT_オプション設定へ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a keyboard or MIDI signal. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_キーボードまたはMIDI信号を入力してください {
            get {
                return ResourceManager.GetString("TXT_キーボードまたはMIDI信号を入力してください", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rating this song に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_この曲の評価 {
            get {
                return ResourceManager.GetString("TXT_この曲の評価", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_コントロールチェンジ {
            get {
                return ResourceManager.GetString("TXT_コントロールチェンジ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free cymbal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_シンバルフリー {
            get {
                return ResourceManager.GetString("TXT_シンバルフリー", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_すべてONOFF {
            get {
                return ResourceManager.GetString("TXT_すべてONOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_ダークモード {
            get {
                return ResourceManager.GetString("TXT_ダークモード", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_ダークモード_FULL {
            get {
                return ResourceManager.GetString("TXT_ダークモード_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Half に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_ダークモード_HALF {
            get {
                return ResourceManager.GetString("TXT_ダークモード_HALF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * The timing clock signal and the active signal are ignored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_タイミングクロック信号_アクティブ信号は無視します {
            get {
                return ResourceManager.GetString("TXT_タイミングクロック信号_アクティブ信号は無視します", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drums sound に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_ドラムサウンド {
            get {
                return ResourceManager.GetString("TXT_ドラムサウンド", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_ノートオフ {
            get {
                return ResourceManager.GetString("TXT_ノートオフ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_ノートオン {
            get {
                return ResourceManager.GetString("TXT_ノートオン", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hit any cymbal or Enter key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_パッドを叩いてください {
            get {
                return ResourceManager.GetString("TXT_パッドを叩いてください", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a player. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_プレイヤーを選択してください {
            get {
                return ResourceManager.GetString("TXT_プレイヤーを選択してください", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize user DB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_ユーザDBを初期化 {
            get {
                return ResourceManager.GetString("TXT_ユーザDBを初期化", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a song
        ///near {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_ランダムに選択 {
            get {
                return ResourceManager.GetString("TXT_ランダムに選択", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lane opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_レーンの透明度 {
            get {
                return ResourceManager.GetString("TXT_レーンの透明度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not possible to run more than one at a time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_二重起動はできません {
            get {
                return ResourceManager.GetString("TXT_二重起動はできません", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * If there is more than 500 milliseconds between inputs, a blank line will be displayed between them. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_入力と入力の間が500ミリ秒以上開いた場合は間に空行を表示します {
            get {
                return ResourceManager.GetString("TXT_入力と入力の間が500ミリ秒以上開いた場合は間に空行を表示します", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input assignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_入力割り当て {
            get {
                return ResourceManager.GetString("TXT_入力割り当て", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fullscreen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_全画面 {
            get {
                return ResourceManager.GetString("TXT_全画面", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_初期化 {
            get {
                return ResourceManager.GetString("TXT_初期化", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show fast/slow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_判定FASTSLOWの表示 {
            get {
                return ResourceManager.GetString("TXT_判定FASTSLOWの表示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Judge position adjust に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_判定位置調整 {
            get {
                return ResourceManager.GetString("TXT_判定位置調整", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_右 {
            get {
                return ResourceManager.GetString("TXT_右", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discard the changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_変更を破棄していいですか {
            get {
                return ResourceManager.GetString("TXT_変更を破棄していいですか", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show bar number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_小節番号の表示 {
            get {
                return ResourceManager.GetString("TXT_小節番号の表示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show bar/beat lines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_小節線と拍線の表示 {
            get {
                return ResourceManager.GetString("TXT_小節線と拍線の表示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_左 {
            get {
                return ResourceManager.GetString("TXT_左", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize record DB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_成績DBを初期化 {
            get {
                return ResourceManager.GetString("TXT_成績DBを初期化", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_戻る {
            get {
                return ResourceManager.GetString("TXT_戻る", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize song DB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_曲DBを初期化 {
            get {
                return ResourceManager.GetString("TXT_曲DBを初期化", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song not found...
        ///Hit BDx2 (in default SPACEx2) to select song folders. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_曲が見つかりません {
            get {
                return ResourceManager.GetString("TXT_曲が見つかりません", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_曲読み込みフォルダ {
            get {
                return ResourceManager.GetString("TXT_曲読み込みフォルダ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_演奏スピード {
            get {
                return ResourceManager.GetString("TXT_演奏スピード", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movie size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_演奏中の動画サイズ {
            get {
                return ResourceManager.GetString("TXT_演奏中の動画サイズ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shrink to center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_演奏中の動画サイズ_中央寄せ {
            get {
                return ResourceManager.GetString("TXT_演奏中の動画サイズ_中央寄せ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fullscreen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_演奏中の動画サイズ_全画面 {
            get {
                return ResourceManager.GetString("TXT_演奏中の動画サイズ_全画面", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show movie に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_演奏中の動画表示 {
            get {
                return ResourceManager.GetString("TXT_演奏中の動画表示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show wallpaper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_演奏中の壁紙表示 {
            get {
                return ResourceManager.GetString("TXT_演奏中の壁紙表示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current assign to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_現在の割り当て {
            get {
                return ResourceManager.GetString("TXT_現在の割り当て", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_画面モード {
            get {
                return ResourceManager.GetString("TXT_画面モード", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_確認 {
            get {
                return ResourceManager.GetString("TXT_確認", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_自動演奏 {
            get {
                return ResourceManager.GetString("TXT_自動演奏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_設定を初期化 {
            get {
                return ResourceManager.GetString("TXT_設定を初期化", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_設定完了 {
            get {
                return ResourceManager.GetString("TXT_設定完了", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_設定完了_戻る {
            get {
                return ResourceManager.GetString("TXT_設定完了_戻る", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rating に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_評価 {
            get {
                return ResourceManager.GetString("TXT_評価", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ❤ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_評価1 {
            get {
                return ResourceManager.GetString("TXT_評価1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ❤❤ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_評価2 {
            get {
                return ResourceManager.GetString("TXT_評価2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ❤❤❤ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_評価3 {
            get {
                return ResourceManager.GetString("TXT_評価3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ❤❤❤❤ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_評価4 {
            get {
                return ResourceManager.GetString("TXT_評価4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ❤❤❤❤❤ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_評価5 {
            get {
                return ResourceManager.GetString("TXT_評価5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No rating に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_評価なし {
            get {
                return ResourceManager.GetString("TXT_評価なし", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Segoe UI emoji に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_評価記号用フォント {
            get {
                return ResourceManager.GetString("TXT_評価記号用フォント", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scroll speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_譜面スピード {
            get {
                return ResourceManager.GetString("TXT_譜面スピード", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size follows volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TXT_音量によるサイズ変化 {
            get {
                return ResourceManager.GetString("TXT_音量によるサイズ変化", resourceCulture);
            }
        }
    }
}
